"""Added extra columns to the users table

Revision ID: 0eac3c1c8a95
Revises: aa95c8b45326
Create Date: 2026-01-17 11:53:31.344637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eac3c1c8a95'
down_revision = 'aa95c8b45326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_name')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('skills')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
